# .travis.yml
# Configure Travis CI service to build bakefile
#
language: python
python:
    - "2.6"
    - "2.7"

os:
    - linux
    - osx

before_install:
  - "git submodule update --init --recursive"

install:
    - "pip install Sphinx"
    - "pip install pytest"
    - "pip install clint"

script: "make test"

notifications:
  email:
    recipients:
      - vz-bakefile@zeitlins.org
  on_success: change # [always|never|change] # default: change
  on_failure: always # [always|never|change] # default: always
